export const Languages = [
    {val:'ar-EG',name:'Arabic - EG'},
    {val:'zh-CN',name:'Chinese - CN'},
    {val:'zh-HK',name:'Chinese - HK'},
    {val:'zh-TW',name:'Chinese - TW'},
    {val:'da-DK',name:'Danish - DK'},
    {val:'nl-NL',name:'Dutch - NL'},
    {val:'en-GB',name:'English - GB'},
    {val:'en-US',name:'English - US'},
    {val:'de-DE',name:'German - DE'},
    {val:'es-ES',name:'Spanish - ES'},
    {val:'fi-FI',name:'Finnish - FI'},
    {val:'fr-FR',name:'French - FR'},
    {val:'hi-IN',name:'Hindi - IN'},
    {val:'it-IT',name:'Italian - IT'},
    {val:'ja-JP',name:'Japanese - JP'},
    {val:'ko-KR',name:'Korean - KR'},
    {val:'nb-NO',name:'Norwegian - NO'},
    {val:'pl-PL',name:'Polish - PL'},
    {val:'pt-BR',name:'Portuguese - BR'},
    {val:'pt-PT',name:'Portuguese - PT'},
    {val:'ru-RU',name:'Russian - RU'},
    {val:'sv-SE',name:'Swedish - SE'},
    {val:'ta-IN',name:'Tamil (India)'},
    {val:'th-TH',name:'Thai (Thailand)'},
    {val:'tr-TR',name:'Turkish (Turkey)'},
    {val:'uk-UA',name:'Ukrainian (Ukraine)'},
    {val:'vi-VN',name:'Vietnamese (Vietnam)'},
    {val:'fa-IR',name:'Persian (Iran)'},
    {val:'lo-LA',name:'Lao (Laos)'},
    {val:'ms-MY',name:'Malay (Malaysia)'},
    {val:'mn-MN',name:'Mongolian (Mongolia)'},
    {val:'id-ID',name:'Indonesian (Indonesia)'},
]
